### PR TITLE
Modify schema to store the fullname as well

### PR DESCRIPTION
**Pull request by ktf**

### CODE REVIEW

**Comment by ktf** [comment]
@dberzano This is what we need on the alice-github side to support for full names.

**Comment by dberzano** [comment]
You're faster at coding than thinking :-)

I think we can merge it. Before deploying it however I need to adapt the mapping part as the output format from the API clearly changed now, am I right?

**Comment by ktf** [comment]
Yes, you are right.

**Comment by dberzano** [comment]
So instead of:

```
{"login_mapping":{"simmons":"brinick"}}
```

I should get:

```
{"login_mapping":{"simmons":{"user_github":"brinick","fullname":"Brinick Simmons"}}}
```

if I am not mistaken. Let me do a pr and deal with this.

**Pull request merged**
